import Head from 'next/head'
import React, { useCallback, useEffect, useState } from 'react';
import { Container, CssBaseline } from '@mui/material';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { CallistoService, speak, SpeechResult, SpeechInputAdapter } from '@bitmetro/callisto';

import { ListenButton } from '../src/components/listen-button';
import { Results } from '../src/components/results';
import { Logo } from '../src/components/logo';

import { funnyPlugin } from '../src/plugins/funny.plugin';
import { weatherPlugin } from '../src/plugins/weather.plugin';
import { wikipediaPlugin } from '../src/plugins/wikipedia.plugin';
import { jokesPlugin } from '../src/plugins/jokes.plugin';

const darkTheme = createTheme({
  palette: {
    mode: 'dark'
  }
});

const callisto = new CallistoService();
callisto.applyPlugins(weatherPlugin, wikipediaPlugin, jokesPlugin, funnyPlugin)

const App: React.FC = () => {
  const [speechInputAdapter, setSpeechInputAdapter] = useState<SpeechInputAdapter | null>(null);
  const [speechResponse, setSpeechResponse] = useState<SpeechResult | null>(null);

  useEffect(() => {
    if (typeof window !== undefined) {
      const speechAdapter = new SpeechInputAdapter()
      callisto.addInputAdapter(speechAdapter);

      callisto.addEventHandlers({
        onMatchingInteractionFound: async match => !match && await handleResponse("Sorry, I don't understand."),
        onResponse: async response => await handleResponse(response.responseText),
      })

      setSpeechInputAdapter(speechAdapter);
    }
  }, [])

  const handleResponse = useCallback(async (text: string) => {
    const result = speak(text);
    setSpeechResponse(result);
    await result.promise;
  }, [])

  const handleCancelClick = () => {
    if (speechResponse) {
      speechResponse.cancel();
    }
  }

  return (
    <div>
      <Head>
        <title>Callisto | BitMetro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />

        {!!speechInputAdapter && (
          <Container maxWidth="sm">
            <div style={{ height: 'calc(100vh - 180px)', padding: 20 }}>
              <Logo />
              <Results speechInputAdapter={speechInputAdapter} />
            </div>

            <div>
              <ListenButton speechInputAdapter={speechInputAdapter} onCancel={handleCancelClick} />
            </div>
          </Container>
        )}
      </ThemeProvider>
    </div>
  );
}

export default App;
