name: Release

on:
  push:
    tags:
      - "*"

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: bitmetro/callisto-server:${{ github.ref_name }}
          push: true
          build-args: |
            SCOPE=server
            PORT=8080

  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: bitmetro/callisto-server:${{ github.ref_name }}
          push: true
          build-args: |
            SCOPE=server
            PORT=3000
